version: "3.6"
services:
  setup:
    image: docker/compose:${DOCKER_COMPOSE_VERSION}
    working_dir: "${PWD}"
    cap_add: ['SYS_ADMIN']
    environment:
      - "PWD=${PWD}"
      - "ELASTIC_PASSWORD"
      - "ELASTIC_VERSION"
      - "TAG"
      - "ELASTIC_PORT"
      - "ELASTIC_PORT2"
      - "KIBANA_PORT"
      - "APM_PORT"
      - "APM_LOG_LEVEL"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}:${PWD}"
    entrypoint: ["/bin/ash", "-c"]
    command: ['cat ./scripts/setup.sh | tr -d "\r" | ash']

    # command: ["./scripts/setup.sh"]