apm-server.frontend.enabled: true
apm-server.host: "0.0.0.0:${APM_PORT}"

output.elasticsearch:
  hosts: ['elasticsearch:${ELASTIC_PORT}']
  protocol: "http"
  username: elastic
  # Read PW from apm-server.keystore
  password: "${ELASTIC_PASSWORD}"
  ssl.enabled: false
  #ssl.certificate_authorities: ["/usr/share/apm-server/certs/ca/ca.crt"]

setup.kibana:
  host: "http://kibana:${KIBANA_PORT}"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  protocol: "http"
  ssl.enabled: false
  #ssl.certificate_authorities: ["/usr/share/apm-server/certs/ca/ca.crt"]
