# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:${ELASTIC_PORT}
# elasticsearch.password is stored in `kibana.keystore`
elasticsearch.username: ${ELASTIC_USERNAME}
#elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/ca/ca.crt"]
server.ssl.enabled: false
#server.ssl.certificate: /usr/share/kibana/config/certs/kibana/kibana.crt
#server.ssl.key: /usr/share/kibana/config/certs/kibana/kibana.key
xpack.monitoring.ui.container.elasticsearch.enabled: true
